---
title: "second approach"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F}
#library(R2jags)
library(R2jags)
library(tidyverse)
library(lubridate)
```

```{r}
leaders_data <- get(load("Leaders.RData"))

leaders_data$Censored <- as.factor(leaders_data$Censored)
leaders_data$Type <- as.factor(leaders_data$Type)
leaders_data$Age.Event <- as.numeric(leaders_data$Age.Event)
summary(leaders_data)
```

# Boxplot of age (Age.Event) by Type
```{r}
ggplot(data = leaders_data) +
  geom_boxplot(aes(x = Type, y = Age.Event))

ggplot(data = leaders_data) +
  geom_point(aes(x = Birth.Date, y = Age.Event))
```

# THIS IS OUR MODEL
$$
T_i \sim Weibull(\alpha, \mu) \\
log(\mu) = \beta_0 + \beta_1x_{i1}+\beta_2x_{i2}+...+\beta_px_{ip}\\
$$
Log of mu is done so that the mu parameter is always positive (the support on mu in Weibull is that mu > 0)

# More specificically
## WILL ADD INTERACTION LATER
$$
T_i \sim Weibull(\alpha, \mu_i) \\
\log(\mu_i) = \beta_0+\beta_1 \text{(Year of Birth_i)}+\beta_2 \text{(Leadership_i = UsPres)} + \beta_3\text{(Leadership_i = ChinaEmp)} \\
+ \beta_4\text{(Leadership_i = DalaiLama)} +\beta_5\text{(Leadership_i = JapanEmp)} \\
+ \beta_6\text{(Year of Birth_i * (Leadership_i = UsPres))} \\
+ \beta_7\text{(Year of Birth_i * (Leadership_i = ChinaEmp))} \\
+ \beta_8\text{(Year of Birth_i * (Leadership_i = DalaiLama))} \\
+ \beta_9\text{(Year of Birth_i * (Leadership_i = JapanEmp))}
$$


# Data Cleaning
```{r}
leaders_data$Birth.Year <- year(leaders_data$Birth.Date)

leaders_data <- leaders_data %>%
  mutate(TypeChinaEmp = as.factor(case_when(Type == "ChinaEmp" ~ 1,
                             TRUE ~ 0)),
         TypeDalaiLama = as.factor(case_when(Type == "DalaiLama" ~ 1,
                                   TRUE ~ 0)),
         TypeJapanEmp = as.factor(case_when(Type == "JapanEmp" ~ 1, 
                                  TRUE ~ 0)),
         TypePope = as.factor(case_when(Type == "Pope" ~ 1, 
                              TRUE ~ 0)),
         TypeUsPres = as.factor(case_when(Type == "UsPres" ~ 1,
                                TRUE ~ 0)))

leaders_nopred <- leaders_data %>%
  filter(!(Name %in% c("14th Dalai Lama (Tenzin Gyatso)", "Naruhito (Emperor Reiwa)", "Barack Obama", "Francis")))

survival_raw <- leaders_nopred$Age.Event
n <- length(survival_raw)

censored <- leaders_nopred$Censored
survival <- ifelse(censored == 0, survival_raw, NA)

censoring_limits <- ifelse(censored == 0, 120, survival_raw)
x_1 <- leaders_nopred$Birth.Year - mean(leaders_nopred$Birth.Year)
x_2 <- leaders_nopred$TypeUsPres
x_3 <- leaders_nopred$TypeChinaEmp
x_4 <- leaders_nopred$TypeDalaiLama
x_5 <- leaders_nopred$TypeJapanEmp
# add interaction b/w Birth.Year and Type
x_6 <- x_1*as.numeric(as.character(x_2))
x_7 <- x_1*as.numeric(as.character(x_3))
x_8 <- x_1*as.numeric(as.character(x_4))
x_9 <- x_1*as.numeric(as.character(x_5))
```


```{r}
set.seed(123)
second_approach <- function() {
  for(i in 1:n_censored) {
    z_censored[i] ~ dpois(phi_censored[i])
    phi_censored[i] <- mu_censored[i] * pow(t_censored[i], r)
    mu_censored[i] <- exp(beta_censored[i])
    beta_censored[i] <- beta_0 + beta_1*x_1_censored[i] + beta_2*x_2_censored[i] + beta_3*x_3_censored[i] + beta_4*x_4_censored[i] + beta_5*x_5_censored[i] + beta_6*x_6_censored[i] + beta_7*x_7_censored[i] + beta_8*x_8_censored[i] + beta_9*x_9_censored[i]
  }
  
  for(j in 1:n_non_censored) { #total rows - 7 ** 7 are censored, rest are not censored
    survival_non_censored[j] ~ dweib(r, mu[j])
    mu[j] <- exp(beta[j])
    beta[j] <- beta_0 + beta_1*x_1_non_censored[j] + beta_2*x_2_non_censored[j] + beta_3*x_3_non_censored[j] + beta_4*x_4_non_censored[j] + beta_5*x_5_non_censored[j] + beta_6*x_6_non_censored[j] + beta_7*x_7_non_censored[j] + beta_8*x_8_non_censored[j] + beta_9*x_9_non_censored[j]
  }
  
  beta_0 ~ dnorm(0.0, 1.0E-3) # Prior on beta_0 is normal with low precision
  beta_1 ~ dnorm(0.0, 1.0E-3) # Prior on beta_1 is normal with low precision
  beta_2 ~ dnorm(0.0, 1.0E-3) # Prior on beta_2 is normal with low precision
  beta_3 ~ dnorm(0.0, 1.0E-3) # Prior on beta_3 is normal with low precision
  beta_4 ~ dnorm(0.0, 1.0E-3) # Prior on beta_4 is normal with low precision
  beta_5 ~ dnorm(0.0, 1.0E-3) # Prior on beta_5 is normal with low precision
  beta_6 ~ dnorm(0.0, 1.0E-3) # Prior on beta_6 is normal with low precision
  beta_7 ~ dnorm(0.0, 1.0E-3) # Prior on beta_7 is normal with low precision
  beta_8 ~ dnorm(0.0, 1.0E-3) # Prior on beta_8 is normal with low precision
  beta_9 ~ dnorm(0.0, 1.0E-3) # Prior on beta_9 is normal with low precision
  r ~ dexp(1) # Prior on r
  
  # Predictive distribution of age at the new values
  beta_Francis <- beta_0 + beta_1*year_Francis 
  mu_Francis <- exp(beta_Francis)
  survival_Francis ~ dweib(r, mu_Francis) %_% T(present_length_Francis, upper_length) 
  age_Francis_predictive <- survival_Francis 
  
  beta_Obama <- beta_0 + beta_2*year_Obama + beta_6*year_Obama
  mu_Obama <- exp(beta_Obama)
  survival_Obama ~ dweib(r, mu_Obama) %_% T(present_length_Obama, upper_length) 
  age_Obama_predictive <- survival_Obama 
  
  beta_Dalai <- beta_0 + beta_4*year_Dalai + beta_8*year_Dalai
  mu_Dalai <- exp(beta_Dalai)
  survival_Dalai ~ dweib(r, mu_Dalai) %_% T(present_length_Dalai, upper_length) 
  age_Dalai_predictive <- survival_Dalai
  
  beta_Naruhito <- beta_0 + beta_5*year_Naruhito + beta_9*year_Naruhito
  mu_Naruhito <- exp(beta_Naruhito)
  survival_Naruhito ~ dweib(r, mu_Naruhito) %_% T(present_length_Naruhito, upper_length) 
  age_Naruhito_predictive <- survival_Naruhito
}
```


```{r}
censored_dex = which(censored==1) # index of ppl who are censored

z_censored <- rep(0, length(censored_dex))
t_censored <- censoring_limits[censored_dex]
x_1_censored <- x_1[censored_dex] 
x_2_censored <- x_2[censored_dex] 
x_3_censored <- x_3[censored_dex]
x_4_censored <- x_4[censored_dex]
x_5_censored <- x_5[censored_dex]
x_6_censored <- x_6[censored_dex]
x_7_censored <- x_7[censored_dex]
x_8_censored <- x_8[censored_dex]
x_9_censored <- x_9[censored_dex]


n_censored <- length(censored_dex)
#

survival_non_censored <- survival[-censored_dex] # Remove ALL ALIVE PEOPLE
x_1_non_censored <- x_1[-censored_dex]
x_2_non_censored <- x_2[-censored_dex]
x_3_non_censored <- x_3[-censored_dex]
x_4_non_censored <- x_4[-censored_dex]
x_5_non_censored <- x_5[-censored_dex]
x_6_non_censored <- x_6[-censored_dex]
x_7_non_censored <- x_7[-censored_dex]
x_8_non_censored <- x_8[-censored_dex]
x_9_non_censored <- x_9[-censored_dex]

n_non_censored <- length(survival_non_censored)

birth_year_Francis <- leaders_data$Birth.Year[leaders_data$Name == "Francis"]
year_Francis <- birth_year_Francis - mean(leaders_data$Birth.Year) # center on leaders or leaders_nopred?
present_length_Francis <- leaders_data$Age.Event[leaders_data$Name =="Francis"]

birth_year_Obama <- leaders_data$Birth.Year[leaders_data$Name == "Barack Obama"]
year_Obama <- birth_year_Obama - mean(leaders_data$Birth.Year) # center on leaders or leaders_nopred?
present_length_Obama <- leaders_data$Age.Event[leaders_data$Name =="Barack Obama"]

birth_year_Dalai <- leaders_data$Birth.Year[leaders_data$Name == "14th Dalai Lama (Tenzin Gyatso)"]
year_Dalai <- birth_year_Dalai - mean(leaders_data$Birth.Year) # center on leaders or leaders_nopred?
present_length_Dalai <- leaders_data$Age.Event[leaders_data$Name =="14th Dalai Lama (Tenzin Gyatso)"]

birth_year_Naruhito <- leaders_data$Birth.Year[leaders_data$Name == "Naruhito (Emperor Reiwa)"]
year_Naruhito <- birth_year_Naruhito - mean(leaders_data$Birth.Year) # center on leaders or leaders_nopred?
present_length_Naruhito <- leaders_data$Age.Event[leaders_data$Name =="Naruhito (Emperor Reiwa)"]


upper_length <- 120

data_Popes_second_approach <- list("n_censored",
                                   "n_non_censored",
                                   "z_censored",
                                   "t_censored",
                                   "x_1_censored",
                                   "x_2_censored",
                                   "x_3_censored",
                                   "x_4_censored",
                                   "x_5_censored",
                                   "x_6_censored",
                                   "x_7_censored",
                                   "x_8_censored",
                                   "x_9_censored",
                                   "survival_non_censored",
                                   "x_1_non_censored",
                                   "x_2_non_censored",
                                   "x_3_non_censored",
                                   "x_4_non_censored",
                                   "x_5_non_censored",
                                   "x_6_non_censored",
                                   "x_7_non_censored",
                                   "x_8_non_censored",
                                   "x_9_non_censored", 
                                   "year_Francis",
                                   "year_Obama", 
                                   "year_Dalai",
                                   "year_Naruhito",
                                   "present_length_Francis", 
                                   "present_length_Obama",
                                   "present_length_Dalai",
                                   "present_length_Naruhito",
                                   "upper_length")

Bayesian_Popes_second_approach <- jags(data = data_Popes_second_approach,  
                                      parameters.to.save = c("beta_0",
                                                             "beta_1",
                                                             "beta_2", "beta_3", "beta_4", "beta_5",
                                                             "beta_6","beta_7", "beta_8", "beta_9",
                                                             "r", "age_Francis_predictive",
                                                             "age_Obama_predictive","age_Dalai_predictive","age_Naruhito_predictive"), 
                                      n.iter = 50000, 
                                      n.chains = 3,
                                      model.file = second_approach)

Bayesian_Popes_second_approach
```

```{r}
library(coda)
#res = data.frame(Bayesian_Popes_second_approach$BUGSoutput$sims.array)
res = data.frame(Bayesian_Popes_second_approach$BUGSoutput$sims.matrix)
colnames(res) <- gsub("^.*\\.","", colnames(res) )

#par(mfrow= c(2,2))
lapply(seq(1,length(res)), function(i) {
  #jpeg(paste0(colnames(res)[i], "_traceplot.jpeg"))
  traceplot(as.mcmc(res[,i]), smooth = FALSE, type = "l",
            xlab = "Iterations", ylab = colnames(res)[i],
            main = paste("Traceplot of ", colnames(res)[i]))
  #dev.off()
})

# tps <- function(var){
#   ggplot(res, aes_(y=as.name(var), x=seq(1,nrow(res)))) + 
#     geom_line() +
#     labs(title=paste("Traceplot of ", as.name(var)),
#          x ="Iterations", y = as.name(var))
# }
# lapply(names(res), tps)
```

```{r}
library(ggplot2)
res_lag1 = lapply(seq(1:length(res)), function(i) {
  lres = lag(res[,i],1)
  plot(y=res[,i], x= lres, 
       xlab = paste0(colnames(res)[i], "-1"),
       ylab = paste0(colnames(res)[i]),
       main = paste("Lag-1 Scatter Plot of", colnames(res)[i]))
})
```

```{r}
#par(mfrow= c(2,2))
lapply(seq(1,length(res)), function(i) { 
  #jpeg(paste0(colnames(res)[i], "_acf.jpeg"))
  acf(res[,i], xlab = "Lag", ylab = "ACF", 
            main = paste("ACF Plot of ", colnames(res)[i]))
  #dev.off()
})
```
